#!/usr/bin/env bash
## Functions library

get_palette() {
    # Extract the 5 predominant colors from input image
    local _input=$1
    palette=$(convert $_input -geometry 16x16 +dither -colors 5 -unique-colors txt:)
    echo "$palette"
}

get_color_from_palette() {
    # Given a color palette and a color ID, returns the correspondant HEX code
    local _palette=$1
    local _color_id=${2-0}
    color=$(echo "$_palette" | grep -e "^$_color_id,0" | cut -d' ' -f4)
    echo $color
}

surufy() {
    # compose tile, logo outline and actual logo
    local _input=$1
    local _format=$2
    local _color=$3
    local _shadow=$4
    local _output=$5
    convert \( "tile-"$_format".png" -fill "$_color" -tint 100 -modulate 130,100,100 \) \
            \( $_input[$_format] -resize 81%  -background $_shadow -shadow 60x1 \) -gravity center -composite \
            \( $_input[$_format] -resize 80% \)\
            -gravity center -composite $_output
}
